<template>
  <div class="col-12 text-justify">
   <p>
     POLÍTICAS DE INSPECCIÓN. Las inspecciones realizadas por CDA CHECK AND GO S.A.S. tendrán como referencia únicamente las normas técnicas o legales vigentes, en ningún caso se utilizarápara la adopción o modificación de procedimientos o instructivos criterios diferentes a los señalados en esas normas o las que las adicionen o modifiquen; nunca podrán usarse pautas de tipo subjetivo, que busquen limitar o reducir el acceso de los servicios de inspección a un grupo determinado. Los parámetros de evaluación y medición de las inspecciones son los que señalen las normas técnicas o los reglamentos.
   </p>
   <p> La imparcialidad, independencia e integridad son principios que rigen de manera absoluta las actuaciones de CDA CHECK AND GO S.A.S. como Organismo de Inspección y que son de obligatoria observancia por parte de su personal. CDA CHECK AND GO S.A.S. es responsable de los bienes y elementos de propiedad del usuario entregados para efectos de la inspección técnico mecánica, excepto en caso de fuerza mayor o caso fortuito o cuando el daño se produzca como consecuencia de la exigencia técnica de la prueba, no es responsable por objetos de valor, dinero u otros bienes dejados en el vehículos y que no hayan sido declarados en el inventario.
   </p><p> DECLARACIÓN DE IMPARCIALIDAD: CDA CHECK AND GO S.A.S. establece que sus actividades de inspección de motocicletas se ceñirán bajo la regla de imparcialidad e independencia y por tanto proscribe cualquier presión que puede resultar de relaciones comerciales, financieras, convenios, actividades de sus funcionarios, relaciones o actividades de sus directivos y socios de la compañía. Las revisiones preventivas y los avalúos no tendrán ninguna consideración o incidencia que afecte la imparcialidad aún en el evento en que un usuario tome dichos servicios y requiera realizar la revisión tecno mecanica y de emisiones contaminantes oficial.
  </p><p> CDA CHECK AND GO S.A.S. como Organismo de Inspección ejecutarátodas sus actividades de acuerdo a los principios de buena fe, lealtad y honorabilidad señalados en la Constitución Nacional, el Código de Comercio y demás normas que las modifiquen o adicionen. En especial CDA CHECK AND GO S.A.S. evitarásiempre la práctica de conductas constitutivas de competencia desleal, o que busquen restringir la competencia.
  </p><p> Todas las actuaciones de CDA CHECK AND GO S.A.S.. como Organismo de Inspección son públicas, en tal sentido CDA CHECK AND GO S.A.S.. se obliga a prestar total cooperación a las autoridades competentes que asílo requieran, siempre y cuando esto no contravenga nuestras obligaciones de confidencialidad de la información de los clientes.
  </p><p>  POLITICAS DE CONFIDENCIALIDAD: Excepto que la Ley o las autoridades de acreditación o las demás competentes lo requieran, CDA CHECK AND GO S.A.S., trataráde manera confidencial y no revelaráa terceros, sin previo consentimiento escrito del usuario, la información que repose en sus archivos o que fuere conocida y/o mantenida en posesión de sus funcionarios durante el curso de las inspecciones.
  </p><p>  En ejercicio de la actividad de inspección y por disposición legal, CDA CHECK AND GO S.A.S., al momento de la recepción (orden de servicio) facturación y registro de la motocicleta, debe recaudar información personal del usuario, correspondiente al nombre y apellido del propietario y/o tenedor de la motocicleta, número de la cédula de ciudadanía, dirección, teléfono, correo electrónico, número y categoría de la licencia de conducción, seguro obligatorio y toda la información correspondiente a la motocicleta. La información personal y técnica antes señalada, tiene como OBJETIVO, el registro y reporte ante el RUNT, SICOV, ONAC, CORTOLIMA, SUPERPUESTOS, MINISTERIO DE TRANSPORTE y alimenta la base de datos de CDA CHECK AND GO S.A.S., que la requiere para la expedición del certificado RTMEyEC y/o formato uniforme de resultados de la revisión técnico mecánica y de emisiones Contaminantes FUR; y realizar actividades de mercadeo, circunscritas a informar al usuario del vencimiento del certificado derevisión, trámites pendientes ante el RUNT, o los organismos de tránsito y/o del seguro obligatorio y cualquier otra información relevante que afecte o modifique, las condiciones del certificado de revisión técnicomecánica y de emisiones contaminantes u ofertas que realiza CDA CHECK AND GO S.A.S.S.A, como también para informar a los usuarios de los nuevos servicios y el vencimiento de estos. El usuario tendráconocimiento del reporte de la información suministrada por él y la acoplada durante el proceso de RTM y EC en el documento de Orden de Servicio toda la información registrada y reportada antes referenciadas están consignadas en el formulario Uniformes de Resultados de la Revisión Técnico Mecánica y de Emisiones Contaminantes FUR. Ademas de lo anterior, autorizo a CDA CHECK AND GO S.A.S. SA. a usar la información que reposa en este documento (orden de servicio) y el recibo del certificado de revisión técnico mecánica, el sistema de registro y cualquier otro mecanismo de recepción de información, para hacer uso de los datos allíconsignados, con el único fin de informarme sobre el vencimiento de la revisión técnico mecánica, asícomo de los cambios legales o reglamentarios que se produzcan al certificado o a la revisión y con fines comerciales en materia de precios y promociones de conformidad a la ley 1581 de 2012
  </p><p>  CDA CHECK AND GO S.A.S. se ha comprometido en el documento Políticas de seguridad de la información a mantener la reserva que le señala la ley, a no divulgar información del usuario si no en los casos que expresamente la ley determina y a darle el uso a la información que el usuario a autorizado.
  </p><p> EXPERIENCIA DEL ORGANISMO DE INSPECCIÓN: CDA CHECK AND GO S.A.S., se encuentra habilitado desde el xx de xxxx de xxxx para realizar las revisiones tecno mecanicás y de emisiones contaminantes a motocicletas desde el xx de xxxx de xxxx, según resolución No. xxxx expedidas por el Ministerio de Transporte. De igual manera se encuentra acreditada por la ONAC mediante certificado No. xxxxxx expedidad desde el xx de xxxx de xxxx y actualmente vigente.
  </p><p>  Autorizo a CDA CHECK AND GO S.A.S. en su calidad de Organismo de Inspección, para que lleve a cabo el servicio solicitado de acuerdo a las normas legales, reglamentarlas y técnicas vigentes sobre la materia, y según los reglamentos y procedimientos internos que el organismo de inspección ha elaborado, de conformidad a la resolución 3768 de 2013 expedida por el Ministerio de Transporte, las NTC 5375 y 5385. Igualmente declaro y acepto que me han sido suficientemente explicadas las condiciones de cada una de las pruebas que componenlos servicios solicitados y el alcance de las mismas; en especial lo referido a las pruebas de emisiones de gases contaminantes reguladas, por la resolución 910 de 2008, expedida por el Ministerio de Ambiente y Desarrollo Territorial y en la NTC 5365.
  </p><p>  Acepto que el vehículo durante el transcurso de las inspecciones sea conducido por el personal técnico de CDA CHECK AND GO S.A.S.
  </p><p>  De conformidad a la resolución 3768 de 2013 expedida por el Ministerio de Transporte, cuando el vehículo o motocicleta a sido reprobado, para la re-inspección que debe realizarse, previamente se hará una inspección sensorial a fin establecer que las condiciones iniciales referidas, a la primera inspección no se ha modificado. En de evidenciarse cambios en esa inspección sensorial, se procederá a realizar nuevamente la inspección técnico mecánica completa, en cuyo caso el usuario deberácancelar el valor correspondiente a la nueva inspección. De no evidenciarse cambios a las condiciones iniciales de inspección, se procederá a inspeccionar aquellos ítems técnicos por lo que réprobo inicialmente. La tarifa que se aplica para el servicio de la revisión Tecno mecanica es la determinada por la resolución 3318 de 2015 del Ministerio de Transporte. El servicio se prestaráen el horario de lunes a Viernes de 7:00a.m. a 6:00p.m.y sábados de 7:00 a.m. a 5.00 p.m.
  </p><p>  OBLIGACIONES DEL USUARIO: Una vez se recepcione el vehículo el usuario debe ubicarse en la sala de espera dispuesta por el CDA-En el evento que el vehículo sometido a la inspección, repruebe algunos de los ítems de esta evaluación, el usuario cuenta con 15 días calendario contados desde la fecha y hora del pago de la revisión tecnico mecanica para realizar los arreglos pertinentes y presentarlo nuevamente a revisión sin costo adicional. Si los 15 días coinciden con un día dominical o feriado el usuario debe presentarse al CDA el día hábil inmediatamente anterior. El pago del servicio de revisión técnico mecánica no implica la expedición del certificado. Este solamente se expide si el vehiculo supera todas las pruebas objeto de revisión conforme lo señalan los reglamentos técnicos. Es deber del usuario abstenerse de dar dadivas, dinero u ofrecimientos indebidos al personal del CDA. Una vez que el vehículo ha sido inspeccionado, no habrádevolución de dinero. Pasados 15 días calendario desde la primera inspección si el vehículo no fue presentado para la re-inspección, o no aprueba ésta en el lapso de los 15días se genera un NUEVO COBRO por el valor de la tarifa señalado por el Ministerio de Transporte, y el proceso se reinicia como si fuera por primera vez.
  </p></div>
</template>
<script>
  export default {
    name: 'q-contract',
  }
</script>
